name: CI
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Verify Node.js Version
      run: node -v

    - name: Run ESLint
      run: |
        npm install eslint
        npx eslint .

    - name: Run Jest Tests
      run: |
        npm install jest
        npx jest

    - name: Run npm audit
      run: npm audit --audit-level=high

    - name: Run Prettier
      run: |
        npm install prettier
        npx prettier --write .

    - name: Send Slack Notification
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,commit,author
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
