name: CI
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Verify Node.js Version Before
      run: node -v
    - run: npm install
    - run: npm test
    - name: Verify Node.js Version After
      run: node -v
